### ISSUE TITLE
apk打开显示未正确激活模块

### ISSUE THREAD

**Issue by Adiao1973** [Xposed-Modules-Repo/com.gswxxn.unlockmilink#1]
<img src="https://user-images.githubusercontent.com/55833348/184672673-65e5232f-44c3-4176-b498-48371c1fab71.jpg" width=30%>
我这边安装完直接调用adb打开的怎么跟你不一样，在你的realse上下载的apk不是LSPosed吗？

**Comment by GSWXXN** [comment]
这个是个 XP模块，需要用 LSPosed 框架激活，请前往 [LSPosed Github 仓库](https://github.com/LSPosed/LSPosed)下载 ，并查询它的使用方法

另外，你首次提交的 Issue 在[这里](https://github.com/GSWXXN/UnlockMiLink/issues/1)

**Comment by Adiao1973** [comment]
好的，谢谢大佬
